Repository talkanbaev-artur/COM392-final-back-team, pull requests merged in 2021-12, with the labels that each got.

#11 Refactored project structure
  .gitignore
  Makefile
  src/animate.cu
  src/animate.h
  src/crack.h
  src/gpuCode.cu
  src/gpuCode.h
  src/hostCode.cpp
  src/hostCode.h
  src/interface.cpp
  src/interface.h
  src/params.h
  src/randLib.h
Labels: refactor

#15 Cleaned up dead code and run modes
  src/animate.cu
  src/crack.h
  src/gpuCode.cu
  src/gpuCode.h
  src/hostCode.cpp
  src/hostCode.h
  src/interface.cpp
  src/interface.h
  src/params.h
Labels: Main loop, refactor

#14 added instructions for g30
  Makefile
  scripts/find_cuda.sh
Labels: enhancement

#19 Created the 1.0 version of the algorithm
  Makefile
  config/config.yml
  scripts/yaml.sh
  src/algorithm/algorithm.cu
  src/algorithm/algorithm.h
  src/algorithm/community.h
  src/algorithm/individual.h
  src/algorithm/objects.cu
  src/algorithm/simulationData.cu
  src/algorithm/simulationData.h
  src/algorithm/sir.cu
  src/algorithm/sir.h
  src/algorithm/virus.h
  src/animate.cu
  src/animate.h
  src/gpuCode.h
  src/hostCode.cpp
  src/interface.cpp
  src/params.h
  src/random.cu
Labels: Kernel, Main loop, refactor
